# Generated by Django 4.2 on 2026-01-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DirEnvio", "0001_initial"),
        ("orden", "0002_orden_ordenid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="direccion_envio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DirEnvio.direccionenvio",
            ),
        ),
    ]
