# Generated by Django 4.2 on 2025-12-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_image"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
