# Generated by Django 4.2 on 2025-11-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
